# Generated by Django 3.2 on 2021-04-07 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefExecutiveOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'CEO',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='FinanceAccountCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Account Codes',
            },
        ),
        migrations.CreateModel(
            name='FinanceStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Finance Staff',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('supervisor_approved', models.BooleanField(default=False)),
                ('supervisor_comments', models.TextField(blank=True, null=True)),
                ('finance_approved', models.BooleanField(default=False)),
                ('finance_comments', models.TextField(blank=True, null=True)),
                ('ceo_approved', models.BooleanField(default=False)),
                ('ceo_comments', models.TextField(blank=True, null=True)),
                ('date_supervisor_review', models.DateTimeField(blank=True, null=True)),
                ('date_finace_officer_review', models.DateTimeField(blank=True, null=True)),
                ('date_ceo_approval', models.DateTimeField(blank=True, null=True)),
                ('account_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.financeaccountcodes')),
                ('ceo_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.chiefexecutiveofficer')),
            ],
            options={
                'verbose_name_plural': 'Purchase Requisition',
                'ordering': ['supervisor_approved', '-id'],
            },
        ),
        migrations.CreateModel(
            name='customuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('staff_id', models.CharField(max_length=15, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supervisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'supervisors',
            },
        ),
        migrations.CreateModel(
            name='SupervisorApprovedPurchaseRequisitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_approved', models.BooleanField(default=False)),
                ('supervisor_disapproved', models.BooleanField(default=False)),
                ('disapproval_message', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.purchaserequisition')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.supervisors')),
            ],
            options={
                'verbose_name_plural': 'Supervisor Approved Purchase Requisitions',
            },
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PurReqrequester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='reviewing_finance_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.financestaff'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='reviewing_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.supervisors'),
        ),
        migrations.AddField(
            model_name='financestaff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FinanceApprovedPurchaseRequisitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_approved', models.BooleanField(default=False)),
                ('finance_disapproved', models.BooleanField(default=False)),
                ('disapproval_message', models.TextField(blank=True, null=True)),
                ('finance_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.financestaff')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.supervisorapprovedpurchaserequisitions')),
            ],
            options={
                'verbose_name_plural': 'Finance Approved Purchase Requisitions',
            },
        ),
        migrations.AddField(
            model_name='chiefexecutiveofficer',
            name='ceo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CEOApprovedPurchaseRequisitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo_approved', models.BooleanField(default=False)),
                ('ceo_disapproved', models.BooleanField(default=False)),
                ('disapproval_message', models.TextField(blank=True, null=True)),
                ('ceo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.chiefexecutiveofficer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.financeapprovedpurchaserequisitions')),
            ],
            options={
                'verbose_name_plural': 'CEO Approved Purchase Requisitions',
            },
        ),
    ]
