# Generated by Django 3.2 on 2021-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='description',
            field=models.TextField(),
        ),
    ]
