# Generated by Django 3.2 on 2021-04-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_customuser_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='department',
            new_name='department_field',
        ),
    ]
