# Generated by Django 3.2 on 2021-04-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_rename_department_customuser_department_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='department_field',
            new_name='department',
        ),
    ]
