# Generated by Django 3.2 on 2021-04-09 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_projects_taxilogistics_taxilogisticssupervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxilogisticssupervisor',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
