# Generated by Django 3.2 on 2021-04-10 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_supervisorapprovedpurchaserequisitions_requisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeapprovedpurchaserequisitions',
            name='requisition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.supervisorapprovedpurchaserequisitions'),
        ),
    ]
