# Generated by Django 3.2 on 2021-04-10 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_financeapprovedpurchaserequisitions_requisition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceoapprovedpurchaserequisitions',
            options={'ordering': ['-id'], 'verbose_name_plural': 'CEO Approved Purchase Requisitions'},
        ),
        migrations.AlterModelOptions(
            name='financeapprovedpurchaserequisitions',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Finance Approved Purchase Requisitions'},
        ),
        migrations.AlterModelOptions(
            name='supervisorapprovedpurchaserequisitions',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Supervisor Approved Purchase Requisitions'},
        ),
        migrations.AlterField(
            model_name='taxilogisticssupervisor',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.taxilogistics'),
        ),
    ]
