# Generated by Django 3.2 on 2021-04-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_auto_20210410_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessadvancerequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessadvancerequest',
            name='finance_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessadvancerequest',
            name='finance_staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.financestaff'),
            preserve_default=False,
        ),
    ]
