# Generated by Django 3.2 on 2021-04-12 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_alter_businessadvancerequest_finance_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessadvancerequest',
            name='supervisor_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BARSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.businessadvancerequest')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
