# Generated by Django 3.2 on 2021-04-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_barfinance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barfinance',
            options={'ordering': ['-id'], 'verbose_name_plural': 'BARFinance'},
        ),
        migrations.AlterModelOptions(
            name='barsupervisor',
            options={'ordering': ['-id'], 'verbose_name_plural': 'BARSupervisor'},
        ),
        migrations.AddField(
            model_name='businessadvancerequest',
            name='finance_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
