# Generated by Django 3.2 on 2021-04-12 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_auto_20210412_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
                ('receipt_no', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.PositiveIntegerField()),
                ('total_reimbursed', models.IntegerField()),
                ('Finance_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.financestaff')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.barfinance')),
            ],
            options={
                'verbose_name_plural': 'BusinessExpenseReport',
                'ordering': ['-id'],
            },
        ),
    ]
