# Generated by Django 3.2 on 2021-04-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_businessexpensereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessexpensereport',
            name='receipt',
            field=models.ImageField(null=True, upload_to='receipts'),
        ),
    ]
