# Generated by Django 3.2 on 2021-04-12 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_businessexpensereport_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessexpensereport',
            name='Finance_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.financestaff'),
        ),
    ]
