# Generated by Django 3.2 on 2021-04-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_alter_businessexpensereport_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessadvancerequest',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
