# Generated by Django 3.2 on 2021-04-13 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_businessadvancerequest_reported'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessExpenseReportFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('finance_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.financestaff')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.businessexpensereport')),
            ],
            options={
                'verbose_name_plural': 'BusinessExpenseReportFinance',
                'ordering': ['-id'],
            },
        ),
    ]
