# Generated by Django 3.2 on 2021-04-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_businessexpensereport_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessexpensereport',
            name='finance_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
