# Generated by Django 3.2 on 2021-05-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0026_auto_20210505_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='signature',
        ),
    ]
