# Generated by Django 3.2 on 2021-04-13 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0024_businessexpensereport_finance_comments'),
        ('Forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingMIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodging', models.PositiveIntegerField()),
                ('mie', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'LodgingMIE',
            },
        ),
        migrations.CreateModel(
            name='TravelAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('destination', models.CharField(max_length=20)),
                ('purpose', models.TextField()),
                ('period', models.CharField(max_length=20)),
                ('accommodation', models.BooleanField(default=False)),
                ('airticket', models.BooleanField(default=False)),
                ('taxi', models.BooleanField(default=False)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('project_to_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.projects')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.supervisors')),
            ],
            options={
                'verbose_name_plural': 'TravelAuthorization',
            },
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
