# Generated by Django 3.2 on 2021-04-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0002_auto_20210413_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('receipt_no', models.CharField(max_length=200)),
                ('receipt', models.ImageField(upload_to='receipts')),
                ('amount', models.PositiveIntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.travelauthorization')),
            ],
            options={
                'verbose_name_plural': 'Other',
            },
        ),
    ]
