# Generated by Django 3.2 on 2021-04-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0003_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts'),
        ),
        migrations.AlterField(
            model_name='other',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
