# Generated by Django 3.2 on 2021-04-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0008_travelauthorization_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ImageField(upload_to='receipts')),
                ('receipt_other', models.ImageField(blank=True, null=True, upload_to='receipts')),
                ('approved', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.travelauthorizationsupervisor')),
            ],
        ),
    ]
