# Generated by Django 3.2 on 2021-04-15 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0009_travelexpensereport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelexpensereport',
            options={'ordering': ['-id'], 'verbose_name_plural': 'TravelExpenseReport'},
        ),
        migrations.AddField(
            model_name='travelexpensereport',
            name='other',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Forms.other'),
        ),
        migrations.AlterField(
            model_name='travelexpensereport',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Forms.travelauthorizationsupervisor'),
        ),
    ]
