# Generated by Django 3.2 on 2021-04-15 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forms', '0010_auto_20210415_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelExpenseReportFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Forms.travelexpensereport')),
            ],
            options={
                'verbose_name_plural': 'TravelExpenseReportFinance',
                'ordering': ['-id'],
            },
        ),
    ]
