# Generated by Django 3.2 on 2021-04-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0011_travelexpensereportfinance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='other',
            options={},
        ),
    ]
