# Generated by Django 3.2 on 2021-04-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0012_alter_other_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelexpensereport',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
