# Generated by Django 3.2 on 2021-04-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0014_travelauthorizationfinance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelauthorizationfinance',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='travelauthorizationfinance',
            name='owner',
        ),
    ]
