# Generated by Django 3.2 on 2021-04-16 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0015_auto_20210416_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelauthorization',
            name='mieandlodging',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Forms.lodgingmie'),
        ),
    ]
