# Generated by Django 3.2 on 2021-04-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0016_travelauthorization_mieandlodging'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelauthorizationsupervisor',
            name='other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Forms.other'),
        ),
    ]
