# Generated by Django 3.2 on 2021-04-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0017_travelauthorizationsupervisor_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelexpensereport',
            name='other',
        ),
    ]
