# Generated by Django 3.2 on 2021-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0018_remove_travelexpensereport_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='mHealthImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'mHealthImages',
                'ordering': ['-id'],
            },
        ),
    ]
