# Generated by Django 3.2 on 2021-04-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0019_mhealthimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelauthorization',
            name='supervisor_comment',
            field=models.TextField(null=True),
        ),
    ]
