# Generated by Django 3.2 on 2021-05-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0020_alter_travelauthorization_supervisor_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelauthorization',
            options={'ordering': ['approved', '-id'], 'verbose_name_plural': 'TravelAuthorization'},
        ),
    ]
