# Generated by Django 3.2 on 2021-05-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0022_leaveapplication_leavedefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='year',
            field=models.PositiveIntegerField(default=2021),
        ),
    ]
