# Generated by Django 3.2 on 2021-05-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0028_leaveapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
