# Generated by Django 3.2 on 2021-05-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0030_auto_20210526_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapplicationcoo',
            options={'verbose_name_plural': 'LeaveApplicationCOO'},
        ),
        migrations.AddField(
            model_name='leaveapplicationsupervisor',
            name='coo_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplicationsupervisor',
            name='coo_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
