# Generated by Django 3.2 on 2021-05-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0031_auto_20210527_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplicationsupervisor',
            name='coo_approved',
            field=models.BooleanField(default=False),
        ),
    ]
