# Generated by Django 3.2 on 2021-05-27 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forms', '0032_alter_leaveapplicationsupervisor_coo_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplicationcoo',
            name='coo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
