# Generated by Django 3.2 on 2021-05-27 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0033_leaveapplicationcoo_coo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaveapplicationcoo',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplicationsupervisor',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
