# Generated by Django 3.2 on 2021-06-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0028_auto_20210524_1332'),
        ('Forms', '0034_auto_20210527_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NonProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OffDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.TextField()),
                ('hours', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.grant')),
                ('non_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Forms.nonproject')),
                ('off_duty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Forms.offduty')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.projects')),
            ],
        ),
    ]
