# Generated by Django 3.2 on 2021-06-03 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forms', '0035_grant_monthlytimesheet_nonproject_offduty'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytimesheet',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
