# Generated by Django 3.2 on 2021-06-03 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forms', '0036_monthlytimesheet_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffDutyTimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50)),
                ('hours', models.PositiveIntegerField()),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.offduty')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
