# Generated by Django 3.2 on 2021-06-03 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0037_offdutytimesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='offdutytimesheet',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
