# Generated by Django 3.2 on 2021-06-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0038_offdutytimesheet_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlytimesheet',
            name='non_project',
        ),
        migrations.RemoveField(
            model_name='monthlytimesheet',
            name='off_duty',
        ),
        migrations.AlterField(
            model_name='offdutytimesheet',
            name='hours',
            field=models.PositiveIntegerField(default=8, editable=False),
        ),
    ]
