# Generated by Django 3.2 on 2021-06-03 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forms', '0039_auto_20210603_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonProjectTimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hours', models.PositiveIntegerField()),
                ('activities', models.TextField()),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.nonproject')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
