export const GET_SUPERVISOR_TRAVEL_AUTHORIZATION =
  "GET_SUPERVISOR_TRAVEL_AUTHORIZATION";
export const GET_SUPERVISOR_TRAVEL_AUTHORIZATION_FAIL =
  "GET_SUPERVISOR_TRAVEL_AUTHORIZATION_FAIL";

export const GET_SPECIFIC_TRAVEL_AUTHORIZATION =
  "GET_SPECIFIC_TRAVEL_AUTHORIZATION";
export const GET_SPECIFIC_TRAVEL_AUTHORIZATION_FAIL =
  "GET_SPECIFIC_TRAVEL_AUTHORIZATION_FAIL";
export const GET_OTHER = "GET_OTHER";
export const GET_OTHER_FAIL = "GET_OTHER_FAIL";
