export const GET_TRAVEL_EXPENSE_REPORT = "GET_TRAVEL_EXPENSE_REPORT";
export const GET_TRAVEL_EXPENSE_REPORT_FAIL = "GET_TRAVEL_EXPENSE_REPORT_FAIL";
export const SPECIFIC_TRAVEL_EXPENSE_REPORT = "SPECIFIC_TRAVEL_EXPENSE_REPORT";
export const SPECIFIC_TRAVEL_EXPENSE_REPORT_FAIL =
  "SPECIFIC_TRAVEL_EXPENSE_REPORT_FAIL";

export const GET_OTHER_TRAVEL_EXPENSE_REPORT =
  "GET_OTHER_TRAVEL_EXPENSE_REPORT";
export const GET_OTHER_TRAVEL_EXPENSE_REPORT_FAIL =
  "GET_OTHER_TRAVEL_EXPENSE_REPORT_FAIL";
