export const START_BUSINESS_ADVANCE_REQUEST = "START_BUSINESS_ADVANCE_REQUEST";
export const BUSINESS_ADVANCE_REQUEST = "BUSINESS_ADVANCE_REQUEST";
export const BUSINESS_ADVANCE_REQUEST_FAIL = "BUSINESS_ADVANCE_REQUEST_FAIL";
export const GET_SUPERVISOR_BUSINESS_ADVANCE_REQUEST =
  "GET_SUPERVISOR_BUSINESS_ADVANCE_REQUEST";
export const GET_SUPERVISOR_BUSINESS_ADVANCE_REQUEST_FAIL =
  "GET_SUPERVISOR_BUSINESS_ADVANCE_REQUEST_FAIL";
export const SPECIFIC_BAR = "SPECIFIC_BAR";
export const SPECIFIC_BAR_FAIL = "SPECIFIC_BAR_FAIL";
