export const PURCHASE_REQUEST = 'PURCHASE_REQUEST';
export const PURCHASE_REQUEST_FAIL = 'PURCHASE_REQUEST_FAIL';
export const SPECIFIC_PURCHASE_REQUEST = 'SPECIFIC_PURCHASE_REQUEST';
export const SPECIFIC_PURCHASE_REQUEST_FAIL = 'SPECIFIC_PURCHASE_REQUEST_FAIL';
export const PURCHASE_REQUEST_DATA = 'PURCHASE_REQUEST_DATA';
export const PURCHASE_REQUEST_DATA_FAIL = 'PURCHASE_REQUEST_DATA_FAIL';
