export const START_TAXI_LOGISTICS = "START_TAXI_LOGISTICS";
export const TAXI_LOGISTICS = "TAXI_LOGISTICS";
export const TAXI_LOGISTICS_FAIL = "TAXI_LOGISTICS_FAIL";
export const GET_SUPERVISOR_TAXILOGISTICS = "GET_SUPERVISOR_TAXILOGISTICS";
export const GET_SUPERVISOR_TAXILOGISTICS_FAIL =
  "GET_SUPERVISOR_TAXILOGISTICS_FAIL";

export const GET_SPECIFIC_TAXI_LOGISTIC = "GET_SPECIFIC_TAXI_LOGISTIC";
export const GET_SPECIFIC_TAXI_LOGISTIC_FAIL =
  "GET_SPECIFIC_TAXI_LOGISTIC_FAIL";
